name: Build and Test
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  local-test:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome
        options: --health-cmd '/opt/bin/check-grid.sh'
    uses: ./.github/workflows/checkout-cache-build.yaml@main
    steps:
      - name: Run local tests
        run: mvn -B test -Pweb-execution -Dsuite=local -Dtarget=local -Dheadless=true -Dbrowser=chrome

  testcontainers-test:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/checkout-cache-build.yaml@main
    steps:
      - name: Run local tests
        run: mvn -B test -Dtarget=testcontainers -Dbrowser=chrome

  browserstack-test:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/checkout-cache-build.yaml@main
    steps:
      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project-name: selenium-lean-java-architecture

      - name: Start BrowserStackLocal Tunnel
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start

      - name: Run browserstack tests
        run: mvn -B test -Pbrowserstack

      - name: Start BrowserStackLocal Tunnel
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop